<?php

return [
    'name' => 'Jago24Barta',
    'name_bn' => 'জাগো২৪বার্তা',
    'slogan' => 'সত্যের সন্ধানে আপোষহীন',
    'description' => 'জাগো২৪বার্তা | সত্যের সন্ধানে আপোষহীন',
    'share_title' => 'Jago24Barta | সত্যের সন্ধানে আপোষহীন',
    'logo' => 'images/jago24barta-logo.png',
    'favicon' => 'favicon.png',
    'category_names' => [
        'agriculture' => 'কৃষি',
        'business' => 'বাণিজ্য',
        'campus' => 'ক্যাম্পাস',
        'country' => 'সারাদেশ',
        'crime-and-corruption' => 'অপরাধ ও দুর্নীতি',
        'economy' => 'অর্থনীতি',
        'education' => 'শিক্ষা',
        'entertainment' => 'বিনোদন',
        'health' => 'স্বাস্থ্য',
        'international' => 'আন্তর্জাতিক',
        'national' => 'জাতীয়',
        'opinion' => 'মতামত',
        'politics' => 'রাজনীতি',
        'রাজনীতি' => 'রাজনীতি',
        'sports' => 'খেলাধুলা',
        'sport' => 'খেলাধুলা',
        'technology' => 'প্রযুক্তি',
        'world' => 'আন্তর্জাতিক',
        'editorial' => 'সম্পাদকীয়',
    ],
    'tag_names' => [
        'bangladesh' => 'বাংলাদেশ',
        'economy' => 'অর্থনীতি',
        'election' => 'নির্বাচন',
        'sports' => 'খেলাধুলা',
        'technology' => 'প্রযুক্তি',
        'world' => 'বিশ্ব',
    ],
    'labels' => [
        'home' => 'প্রচ্ছদ',
        'latest' => 'সর্বশেষ সংবাদ',
        'breaking' => 'ব্রেকিং নিউজ',
        'trending' => 'জনপ্রিয় সংবাদ',
        'search' => 'অনুসন্ধান',
        'categories' => 'বিভাগসমূহ',
        'contact' => 'যোগাযোগ',
        'about' => 'আমাদের সম্পর্কে',
        'advertise' => 'বিজ্ঞাপন',
        'newsroom' => 'নিউজরুম',
        'advertisement' => 'বিজ্ঞাপন',
        'author' => 'প্রতিবেদক',
        'published' => 'প্রকাশিত',
        'read_time' => 'পড়তে সময়',
        'related' => 'আরও সংবাদ',
        'all' => 'সব',
        'no_results' => 'কোনো সংবাদ পাওয়া যায়নি',
    ],
];
